---
title: "TidyTuesday / Anime Data (2019-04-23)"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load libraries

```{r, message=FALSE, warning=FALSE}
library(tidyverse)
library(lubridate)
library(ggthemr)
library(cowplot)
```

# Download data

```{r, message=FALSE, warning=FALSE}
tidy_anime <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-04-23/tidy_anime.csv")
```

# Create new variables and filter data-set

```{r}
tidy_anime <- tidy_anime %>% 
  mutate(start_date_lub = ymd(start_date)) %>% 
  mutate(year = floor_date(start_date_lub, unit = "year")) %>% 
  mutate(decade = year(floor_date(start_date_lub, unit = years(10)))) %>% 
  mutate(decade_fac = as.factor(decade)) %>% 
  filter(!is.na(decade), !is.na(score))
```

# Create plots

```{r, fig.width=10}
ggthemr("flat dark")
p1 <- ggplot(tidy_anime, aes(x = genre, y = decade_fac, fill = score)) +
  geom_tile() +
  scale_fill_distiller(palette = "Spectral", limits = c(0, 10), name = "Score") +
  theme(
    legend.position = "none",
    axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5)
  ) +
  xlab("Genere") + ylab("Decade") +
  ggtitle("Score by genere and decade")
p2 <- ggplot(tidy_anime, aes(x = source, y = decade_fac, fill = score)) +
  geom_tile() +
  scale_fill_distiller(palette = "Spectral", limits = c(0, 10)) +
  theme(
    legend.position = "none",
    axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5),
    axis.ticks.y = element_blank(),
    axis.text.y = element_blank()
  ) +
  xlab("Source") + ylab("") +
  ggtitle("Score by source and decade")

pg <- plot_grid(
  plot_grid(p1, p2, ncol = 2, rel_widths = c(0.66, 0.33)),
  plot_grid(get_legend(p1 + theme(legend.position = "bottom")), 
            ggdraw() + draw_label("Source: MyAnimeList"),
            ncol = 2),
  ncol = 1, rel_heights = c(0.9, 0.1)
)
pg

ggsave(pg, file = "anime_score_by_genere_source_decade.png")
```